version: '2'

networks:
  hf-exp:

services:

  orderer.ksachdeva-exp.com:    
    extends:
      file:  docker-compose-orderer.yaml
      service: orderer.ksachdeva-exp.com

  peer0.org1.ksachdeva-exp.com:
    container_name: peer0.org1.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer0.org1.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org1-peer0:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org1.ksachdeva-exp.com/peers/peer0.org1.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.ksachdeva-exp.com/peers/peer0.org1.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - hf-exp

  peer1.org1.ksachdeva-exp.com:
    container_name: peer1.org1.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer1.org1.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org1-peer1:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org1.ksachdeva-exp.com/peers/peer1.org1.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.ksachdeva-exp.com/peers/peer1.org1.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - hf-exp

  peer0.org2.ksachdeva-exp.com:
    container_name: peer0.org2.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer0.org2.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org2-peer0:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer0.org2.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer0.org2.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - hf-exp

  peer1.org2.ksachdeva-exp.com:
    container_name: peer1.org2.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer1.org2.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org2-peer1:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer1.org2.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.ksachdeva-exp.com/peers/peer1.org2.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
    networks:
      - hf-exp

  peer0.org3.ksachdeva-exp.com:
    container_name: peer0.org3.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer0.org3.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org3-peer0:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer0.org3.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer0.org3.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - hf-exp

  peer1.org3.ksachdeva-exp.com:
    container_name: peer1.org3.ksachdeva-exp.com
    extends:
      file:  docker-peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.ksachdeva-exp.com
      - CORE_PEER_ADDRESS=peer1.org3.ksachdeva-exp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.ksachdeva-exp.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./production/org3-peer2:/var/hyperledger/production
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer1.org3.ksachdeva-exp.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.ksachdeva-exp.com/peers/peer1.org3.ksachdeva-exp.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12053:7053
    networks:
      - hf-exp
